apiVersion: apps/v1
kind: Deployment
metadata:
  name: exploit-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exploit-client
  template:
    metadata:
      labels:
        app: exploit-client
    spec:
      containers:
      - name: client
        image: exploit-client:1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false