apiVersion: apps/v1
kind: Deployment
metadata:
  name: exploit-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exploit-client
  template:
    metadata:
      labels:
        app: exploit-client
    spec:
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: client
        image: exploit-client:1.0
        imagePullPolicy: IfNotPresent

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"

        volumeMounts:
        - name: tmp
          mountPath: /tmp

      volumes:
      - name: tmp
        emptyDir: {}