apiVersion: v1
kind: ServiceAccount
metadata:
  name: restricted-user
  namespace: testns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restricted-pod-access
  namespace: testns
rules:

# Allow basic pod visibility only
- apiGroups: [""]
  resources:
    - pods
    - pods/log
  verbs:
    - get
    - list
    - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restricted-pod-access-binding
  namespace: testns
subjects:
- kind: ServiceAccount
  name: restricted-user
  namespace: testns
roleRef:
  kind: Role
  name: restricted-pod-access
  apiGroup: rbac.authorization.k8s.io