apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-server
  template:
    metadata:
      labels:
        app: vuln-server
    spec:
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: server
        image: vuln-server:1.0
        imagePullPolicy: IfNotPresent

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

        ports:
        - containerPort: 5000

        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"

        volumeMounts:
        - name: tmp
          mountPath: /tmp

      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vuln-server-service
spec:
  selector:
    app: vuln-server
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP